services:
  - type: web
    name: payroll_dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    region: oregon
    plan: free
    branch: main
